spring.application.name: Azure Function - EventGrid
spring.main.banner-mode: off
logging.level.org.springframework.cloud.task: info

resolution : 200
enableCompression : true
compressionType : LZW
connectionString : <Azure Storage Connection String>
containerName : outward
storageblobcreatedevent : Microsoft.Storage.BlobCreated